# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('sid', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular song across whole library', primary_key=True, serialize=False)),
                ('hasVideo', models.BooleanField()),
                ('date', models.DateField()),
            ],
        ),
    ]
