# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SpoTV', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular User', primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('usrname', models.CharField(max_length=200)),
                ('photo', models.FileField(upload_to=None)),
            ],
        ),
    ]
