# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpoTV', '0002_user'),
        ('SpoTV', '0002_auto_20171030_2131'),
    ]

    operations = [
    ]
