# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 08:11
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SpoTV', '0002_youtubeplaylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeplaylist',
            name='playlist',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
