# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpoTV', '0004_auto_20171031_1327'),
        ('SpoTV', '0003_auto_20171031_0411'),
    ]

    operations = [
    ]
