# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SpoTV', '0005_merge_20171031_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='pid',
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(to='SpoTV.Song'),
        ),
        migrations.AlterField(
            model_name='youtubeplaylist',
            name='playlist',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
