# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpoTV', '0006_auto_20171031_1408'),
        ('SpoTV', '0005_merge_20171031_1417'),
    ]

    operations = [
    ]
