# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpoTV', '0003_merge_20171030_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.FileField(upload_to=None),
        ),
    ]
