# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpoTV', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YoutubePlaylist',
        ),
        migrations.AddField(
            model_name='playlist',
            name='videoID',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
